### ISSUE TITLE
Skillslots Requested by everpotions mod ID error

### ISSUE THREAD

**Issue by Aerhtjiz** [Snownee/EverPotion#11]
### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

5.0.0

### Modloader version

43.2.0

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://www.dropbox.com/scl/fi/bfo9i3y3uqzoacoibsf4p/latest.log?rlkey=anhwmt5s6o5sebdkwvwfezu02&dl=0

### Issue description

Minecraft crashes a little after startup with a modpack im creating.

**Comment by Snownee** [comment]
Just install Skill Slots
