### ISSUE TITLE
Creating custom cores

### ISSUE THREAD

**Issue by headhunter12744** [Snownee/EverPotion#12]
### Mod loader

Forge

### Minecraft version

1.18.2

### Mod version

1.18.2

### Modloader version

Forge 40.2.14 (doesn't matter the Forge version)

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Is there a way to create our own ever potion Cores?
Any tutorials? Or will you be able to make for example a custom gui that with help us create in game a core? (For example i want to create a ice resistance core)

**Comment by Snownee** [comment]
I guess you can already do that. It is just not showing on the recipe viewer

**Comment by headhunter12744** [comment]
> I guess you can already do that. It is just not showing on the recipe viewer

If it's possible where and how can I find it? Or how can I customize or add new cores with crafttweaker?

Because I can't anywhere the potion core editor

**Comment by Snownee** [comment]
You can add new core recipes using datapack

**Comment by headhunter12744** [comment]
Ok thank you
