### ISSUE TITLE
not combitable with newest forge

### ISSUE THREAD

**Issue by ZEROX7** [Snownee/EverPotion#4]
* Forge Version: forge-32.0.98
 * Mod Version: EverPotion-1.16.1-2.0.1.jar

[latest.log](https://1drv.ms/u/s!AoGi5ELkm7SZoVFsEbF9IvT3B5je?e=rEpPop)

**Comment by Snownee** [comment]
Hello. Why you think this is caused by EverPotion?

**Comment by ZEROX7** [comment]
ups wrong latest.log XD sry
heres the actual one https://pastebin.com/Lt4AHw5h
