### ISSUE TITLE
how many mobs do i have to kill to unlock a slot for ever potion mod

### ISSUE THREAD

**Issue by pixelboy8569** [Snownee/EverPotion#9]
### Mod loader

Forge

### Minecraft version

1.16.5

### Mod version

2.4.0

### Modloader version

idk

### Modpack info

it not an modpack it ever potion mod alone

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

HOW MANY MOBS DO I HAVE TO KILL TO UNLOCK ANOTHER SLOT IN EVER POTION MOD

**Comment by Chair050** [comment]
Hi, I think the default value is 0.5% on every mob kill. But you can tweak that value in `everpotion-common.toml` .
